<script>
  export let items;
  export let title;
</script>

<svelte:head>
  <title>{title}</title>
</svelte:head>

<h3>{title}</h3>

{#each items as item, i}
  <p class="item">{i}: {JSON.stringify(item)}</p>
{/each}

<footer>
  <p>
    Generated by <a href="https://github.com/mvolfik/gcs-gallery">gcs-gallery</a
    > &copy; 2022 Matěj Volf
  </p>
</footer>

<style>
  p.item {
    color: red;
  }
</style>
