<script>
  import Gallery from "svelte-photoswipe";
  export let items;
  export let title;
</script>

<svelte:head>
  <title>{title}</title>
</svelte:head>

<h3>{title}</h3>

<Gallery images={items} styling="flex" />

<footer>
  <p>
    Generated by <a href="https://github.com/mvolfik/gcs-gallery">gcs-gallery</a
    > &copy; 2022 Matěj Volf
  </p>
</footer>

<style>
  p.item {
    color: red;
  }
</style>
